spring.application.name=That Was Great
spring.main.web-application-type=none
application.title=That Was Great

driverClassName=org.sqlite.JDBC
url=jdbc:sqlite:data/thatwasgreat.db
username=sa
password=sa
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.open-in-view=false
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=false
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace